### ISSUE TITLE
Create UI layout for the "My Grocery List" Page

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#101]
### Task:
Create the UI layout for the "My Grocery List" page according to the Mockups

### Acceptance Criteria:

- [x]  The UI layout should have a heading that says "My Grocery List"
- [x]  There should be space for a Search Bar component below the heading
- [x]  The main section of this page will display Grocery Items of all of the items the user has saved which will be wired up to the DB in another task
![image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/0818edf6-2403-4068-b254-9aa4a54a2412)
