### ISSUE TITLE
Create the Grocery Item component & section on the "My Grocery List" page

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#102]
### Task:
Create the Grocery Ingredient section in the My Grocery List page.

### Acceptance Criteria:
- [ ]  The main section of the user's My Grocery List page should display cards from grocery items that are saved to the user's list in the database
- [ ]  There should be a fetch request set up to pull from the user's saved grocery item api endpoint in the backend project (there's an endpoints file in the docs folder of the project if you need guidance to what the endpoints are) and create each grocery item card off of the saved information.
- [ ]  The grocery item cards should have a Delete/trash can icon as well as the name of the ingredient and the amount/quantity 

![image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/5ba5ffd4-004e-4533-9889-1e5e83405bbb)
