### ISSUE TITLE
Set up the Search Bar functionality on the "My Grocery List" page to search through the user's stored Grocery Items

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#103]
### Task:
The Search Bar component on this page needs configured to only search through a user's saved Grocery Items 

### Acceptance Criteria:
- [ ]  If a user has Grocery Items saved, they should be able to search for them through the Search Bar component
- [ ]  If a user has no favorites saved, they should see a "No grocery items saved yet" message and the search bar component should be disabled or greyed out so the user knows they can't search for anything
- [ ]  This will tie in with the Search Bar component itself, but when the "Search" icon is clicked on, it should have a fetch request to go to the user's saved grocery items endpoint in the backend to pull in any saved items the user has that match the given search criteria
