### ISSUE TITLE
Implement ability for a User to delete a grocery item from their list on the "My Grocery List" page

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#104]
### Task:
The delete button on the Grocery Item Card should remove the Grocery Item from a user's saved items in the DB

### Acceptance Criteria:

- [ ]  When a user clicks on the "Delete" icon, it should display a message/modal that asks the user if they're sure they want to delete this item from their grocery list
- [ ]  If the user clicks "No" the modal should close and no action should happen/nothing should be deleted
- [ ]  If the user clicks "Yes" to confirm that they do want to remove the item from their favorites, this click event should go to a fetch request to an api endpoint that will take the grocery item ID and user ID in the payload to delete the item from the user's Grocery List in the db

![image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/c716ea69-fb2b-4243-97ea-e6b6a2d22d24)
