### ISSUE TITLE
Connect Recipe API

### ISSUE THREAD

**Issue by em-ess** [bethanyann/dsd-cohort-2024#22]
This will involve getting an API key from the chosen recipe API, adding it to the environment variables file in the frontend, and then confirming via Postman or other API tool that the API requests are working

### Task: 
Create the environment variables and anything else needed to connect to the chosen recipe API.  Link to the documentation: https://developer.edamam.com/edamam-docs-recipe-api

### Steps to take to get this set up:

- [x] Create a new account on the Edamam site.  The screenshot below will show the choices, just put your own email address in the input field, create your own password and choose the "Recipe Search API" and "Developer" as the plan options
![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/cb51b651-78a3-4fc0-940f-7d56b246ef3f)

- [x] Once you have successfully created an account, click on the `Accounts` button in the top right of the header, and you will see this modal.  Click on the `Go to Dashboard` button here to navigate to the dashboard overview 
![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/ff5eaed0-62cf-4ec5-b7c6-c77a769a82e4)

- [x] Once you are on the Dashboard page, click on the `Applications` link and you should see the API for the Recipe Search that you created earlier when signing up for an account.  Click on the `View` button next to the Recipe Search API 

![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/245b6ed0-2e24-4902-8090-ce6230a33779)

- [x] On this page, there will be two `keys` listed, you will need to copy these keys and store them in a file in the project. 

![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/c48177f5-cd21-410b-9833-78aace49ac91)

This file is called an `environment` file.  Go into your IDE of choice (IntelliJ or VSCode), open up the Frontend_Application, and create a new file at the root of this project called `.env`

![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/e3b49c59-d5cd-461e-a145-1b7c8eab3602)

In this file, you will put the two application keys from the Edamam api that you just copied.  They will go into the file in this format: 
`APPLICATION_ID=1234567890`  with the key name in all caps, followed by an equals sign and then the key from Edamam.
Make sure to put both keys into the `.env` file
 
- [x] Since this .env file has keys in it that should stay private and not published to a public repository, this .env file should be added to the .gitignore file in the frontend project
- [x] The keys can be privately shared between the cohort members, and each member should create their own local .env file to store the keys in, that way the .env file isn't published to GitHub in the repository.  
- [x] When you get the keys generated and set up, message the team in the chat to let them know you've got the API keys set up and can share with them
- [x] Create a Pull Request in GitHub that includes the addition of the `.env` file to the `.gitignore` file in the Frontend_Application project, and double-check that the `.env` file didn't get added to the PR at all. 
- [x] That's it! You've gotten the API set up to be connected!
