### ISSUE TITLE
Set up User Login API and Implement Validation for Logging in an Existing User

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#40]
Create the API route for when a user logs in and implement validation on the payload

This could include checking to make sure the username/password match as well as sending an error message to the frontend if validation fails

### Task:
Set up an endpoint in the backend to handle a user's registration payload

### Acceptance Criteria:

- [x] An endpoint should exist in the UserController to handle a user's login payload
- [ ] The endpoint function should include validation for the user's data:
- Username & password are not blank
- Username exists
- Username & Password match
- [x] The function should include another method to match the user's entered password with the saved hashed password
- [ ] Return a token to the frontend upon a successful log in attempt
- [ ] Include the Token and user's First & Last Name in the payload returned to the front end.
