### ISSUE TITLE
Set up Backend to Retrieve User from DB Upon a Successful Login Attempt

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#41]
### Task: 

Return a success message or token to the frontend based on the chosen user authentication method

### Acceptance Criteria: 

- [ ] When a user successfully logs in, the backend should create an authentication token
- [ ] The authentication token should be included in the payload returned to the frontend
- [ ] Also included in the payload should be the user's First & Last Name and Email Address.

**Comment by Dissurender** [comment]
Issue #79 peer associated.
