### ISSUE TITLE
Create the "Recipe Card" view in the main section of the Dashboard

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#59]
This will display recipes from the API in a "card" format for the user to scroll through

### Task:
Create the basic layout for the User's Dashboard/My Recipes page

### Acceptance Criteria:

- [ ]  The layout should be responsive to different screen sizes
- [ ]  The cards can display 3 static cards in this section, or it can be turned into a sort of "carousel" where the user can scroll through a few different options
- [ ] The cards should be pulled from the recipe API
- [ ] There should be a click event on the '+' button on the card that will send the recipe ID and the user ID in a payload to the backend to save the associated recipe into a user's favorites

### Screenshot from mockups for reference:

![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/8a97e5dd-c804-424a-aedc-6a400a588b72)
