### ISSUE TITLE
Save Recipe Card to a user's favorite recipes in the DB when the "+" button is  clicked

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#65]
### Task: 

Wire up the API to the backend save a Recipe to a user's favorites when the "+" icon is clicked

![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/080a63a2-0244-4efc-857c-94b1f3d7e9a2)

### Acceptance Criteria:

- [ ] When a user clicks the "+" the User ID and Recipe ID will be sent in a payload to an endpoint in the backend
- [ ] An endpoint should be created to handle the payload and validate that both ID values were included in the payload 
- [ ] This endpoint should handle saving the User ID & the Recipe ID associated with the recipe that was clicked on
- [ ] The backend endpoint should return an error response/message if there was an issue with saving the User with the associated Recipe ID
- [ ] The backend endpoint should return a success response/message if the data was successfully saved without issue

**Comment by Dissurender** [comment]
- /addRecipe - req body contains the recipeId and user email
- /deleteRecipe - req body contains the recipeId and user email
- /getUserFavorites - req body contains the user email

**Comment by Dissurender** [comment]
This issue is handled by #111
