### ISSUE TITLE
Create the Navigation Bar component and Restrict links based on if the user is logged in/logged out

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#86]
### Task: 
 Create a responsive Navigation Bar component and have it display at the top of all pages

### Acceptance Criteria: 

- [ ] The Navigation Bar styling should be response
- [ ] The Navigation Bar should have the Site Logo on the left side that redirects to the Dashboard if the user is not already on the dashboard page AND currently logged in
- [ ] The Navigation Bar should have the Site Logo on the left side that redirects to the Login page if the user is not currently logged in
- [ ] Restrict the page routes and links in the Navigation bar to prevent a user who is not logged in from accessing the Dashboard, My Recipes, My Grocery List, My Preferences, and Recipe Details Modal routes in the Routes as well as the Navigation Bar and only show links to the Log In page and the Register page 
- [ ] When a user is logged in, they should see a "Log Out" link In the navigation bar that when clicked will log the user out and redirect them to the Login page
- [ ] A user who is logged out should not be able to type in the routes for the Dashboard page, My Recipes, My Grocery List, My Preferences, or the Recipe Details Modal and be redirected to anything other than the Log In page
- [ ] A user who is logged out should only see the Logo, and a link to Log in or Register in the Navigation Bar
