### ISSUE TITLE
Create UI layout for the "My Recipes" Page

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#95]
### Task: 
Create the UI layout for the "My Recipes" page according to the Mockups 

### Acceptance Criteria: 
- [ ] The UI layout should have a heading that says "My Recipes" or "My Favorite Recipes" 
- [ ] There should be space for a Search Bar component below the heading
- [ ] The main section of this page will display Recipe Cards of all of the recipes the user has set as their favorites which will be wired up to the DB in another task 

![Image](https://github.com/bethanyann/dsd-cohort-2024/assets/21211634/45e6b816-5a3b-4dd0-8b7b-50c988bebdf1)
