### ISSUE TITLE
Set up the Search Bar functionality on this page to search through the user's favorites

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#96]
### Task: 
The Search Bar component on this page needs configured to only search through a user's favorites and not pull from the API 

### Acceptance Criteria: 

- [ ] If a user has favorites saved, they should be able to search for them through the Search Bar component
- [ ] If a user has no favorites saved, they should see a "No favorites saved yet" message and the search bar component should be disabled or greyed out so the user knows they can't search for anything
- [ ] This will tie in with the Search Bar component itself, but when the "Search" icon is clicked on, it should have a fetch request to go to the user's favorite's endpoint in the backend to pull in any favorites the user has that match the given search criteria
