### ISSUE TITLE
Create the Recipe Card Section on the "My Recipes" page

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#98]
### Task: 
Create the Recipe Card section in the My Recipes page.  The same component used on the Dashboard page can be used for this section as well. 

### Acceptance Criteria: 

- [ ] The main section of the user's My Recipes page should display recipe cards from recipes that are saved to the user's favorites
- [ ] There should be a fetch request set up to pull from the user's favorites api endpoint in the backend project (there's an endpoints file in the docs folder of the project if you need guidance to what the endpoints are) and create each recipe card off of the saved information.  
- [ ] The recipe cards should have the "+" hidden on this page, and a Delete/trash can icon in it's place
