### ISSUE TITLE
Implement ability for a User to delete a recipe from their favorites on the "My Recipe" page

### ISSUE THREAD

**Issue by bethanyann** [bethanyann/dsd-cohort-2024#99]
### Task: 
The delete button on the Recipe Card should remove the Recipe from a user's saved favorites in the DB 

### Acceptance Criteria: 

- [ ] When a user clicks on the "Delete" icon, it should display a message/modal that asks the user if they're sure they want to delete this recipe from their favorites
- [ ] If the user clicks "No" the modal should close and no action should happen/no recipes should be deleted
- [ ] If the user clicks "Yes" to confirm that they do want to remove the recipe as a favorite, this click event should go to a fetch request to an api endpoint that will take the recipe ID and user ID in the payload to delete the recipe from the user's favorites in the db
